### ISSUE TITLE
Example should be renamed to include simpletest

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_AVRprog#11]
Example `avrprog_read_signature.py` should be renamed to ` 	avrprog_read_signature_simpletest.py` to match CircuitPython library standards.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by abkosar** [comment]
Hey! Can I also do this?

**Comment by kattni** [comment]
Go for it!

**Comment by ladyada** [comment]
donnnnnnne!
