### ISSUE TITLE
Examples not beginning with avrprog_ should be renamed

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_AVRprog#12]
There are four examples not beginning with `avrprog_`. They should be renamed to begin with that to fit CircuitPython library standards and clarify which library they are associated with in the examples bundle.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by ladyada** [comment]
examples are all .py

**Comment by ladyada** [comment]
er, all .py examples are renamed. other files are for demo
