### ISSUE TITLE
Would this work on a Raspberry Pi?

### ISSUE THREAD

**Issue by E3V3A** [adafruit/Adafruit_CircuitPython_AVRprog#7]
Looking for a decent Py based AVR programmer, I am wondering is this can also be used for Raspberry Pi 3? 
I would guess not really since the GPIO's would all be different, but perhaps someone could enlighten me to what and where to change this,?

**Comment by ladyada** [comment]
it should 'just' work - this guide can also be used :)
https://learn.adafruit.com/program-an-avr-or-arduino-using-raspberry-pi-gpio-pins
